In [1]:
print("hello world")

hello world


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr=arr*2
print(arr)

[ 2  4  6  8 10]


In [9]:
array=np.array([1,2,3,4,5])
print(array)
print("type of array:",type(array))
print("data type:",array.dtype)


[1 2 3 4 5]
type of array: <class 'numpy.ndarray'>
data type: int64


In [13]:
array=np.array(array,dtype=np.int8)
print(array)
print("no of bytes:",array.nbytes)

[1 2 3 4 5]
no of bytes: 5


"In int8 we can store value upto (-128 to 127)"

In [15]:
float_demo=np.array([1.2,2.3,3.4,4.5])
print(float_demo)
print(type(float_demo))
print("no of bytes:",float_demo.nbytes)


[1.2 2.3 3.4 4.5]
<class 'numpy.ndarray'>
no of bytes: 32


In [16]:
#string
array=np.array(["dinesh","yogitha","karthick","samar","suganth"])
print(array)
print("type of array:",array.dtype)
print("no of bytes:",array.nbytes)

['dinesh' 'yogitha' 'karthick' 'samar' 'suganth']
type of array: <U8
no of bytes: 160


In [20]:
# 0-dimension
array=np.array(1)
print(array)
print("dimesion:",array.ndim)

1
dimesion: 0


In [24]:
#1dimension

arr=np.array([1,2,3,4,5])


# 2-dimension

brr=np.array([
    [1,2,3],
    [4,5,6]
])


# 3-dimension

crr=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [11,22,33],
        [12,13,14]
    ]
])


print(arr)
print("dimension:",arr.ndim)

print(brr)
print("dimension:",brr.ndim)

print(crr)
print("dimension:",crr.ndim)




[1 2 3 4 5]
dimension: 1
[[1 2 3]
 [4 5 6]]
dimension: 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [12 13 14]]]
dimension: 3


In [28]:
#to access the elements
#(layer,start,stop)
print(crr[1][1][1])
#or
print(crr[1,1,1])

13
13
